# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
puts "Cleaning database..."
Card.destroy_all
List.destroy_all
Board.destroy_all
User.destroy_all

puts "Creating User..."
user = User.create!(email: 'demo@example.com', password: 'password', password_confirmation: 'password')

puts "Creating Board..."
board = Board.create!(name: 'Product Roadmap', user: user)

puts "Creating Lists & Cards..."
['Backlog', 'In Progress', 'Done'].each_with_index do |list_name, index|
  list = List.create!(name: list_name, board: board, position: index + 1)

  3.times do |i|
    Card.create!(
      title: "Task #{i + 1} for #{list_name}",
      description: "This is a fake task generated by seeds.",
      list: list,
      position: i + 1
    )
  end
end

puts "Done! Login with demo@example.com / password"
